fsa-streamotion/environment-integration-staging

- env/Chart.yaml
- env/requirements.yaml
chore: Promote foxtel-platform-communication-whispir-api to version 1.0.1
> chore: foxtel-platform-communication-whispir-api to 1.0.1

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.4
> chore: foxtel-platform-general-netflix-api to 1.0.4

- env/requirements.yaml
chore: Promote foxtel-platform-general-account-management-api to version 1.0.2
> chore: foxtel-platform-general-account-management-api to 1.0.2

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.7
> chore: foxtel-platform-general-netflix-api to 1.0.7

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.8
> chore: foxtel-platform-general-netflix-api to 1.0.8

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 0.0.0-PR-13-1-SNAPSHOT
> chore: foxtel-platform-general-netflix-api to 0.0.0-PR-13-1-SNAPSHOT

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.9
> chore: foxtel-platform-general-netflix-api to 1.0.9

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.10
> chore: foxtel-platform-general-netflix-api to 1.0.10

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.11
> chore: foxtel-platform-general-netflix-api to 1.0.11

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.12
> chore: foxtel-platform-general-netflix-api to 1.0.12

- env/requirements.yaml
chore: Promote foxtel-platform-general-netflix-api to version 1.0.13
> chore: foxtel-platform-general-netflix-api to 1.0.13

- env/requirements.yaml
chore: Promote foxtel-platform-general-account-management-api to version 1.0.5
> chore: foxtel-platform-general-account-management-api to 1.0.5

- env/requirements.yaml
chore: Promote foxtel-platform-general-account-management-api to version 1.0.8
> chore: foxtel-platform-general-account-management-api to 1.0.8

- env/requirements.yaml
chore: Promote foxtel-platform-general-account-management-api to version 1.0.19
> chore: foxtel-platform-general-account-management-api to 1.0.19

- env/requirements.yaml
chore: Promote foxtel-platform-general-sales-management-api to version 1.0.6
> chore: foxtel-platform-general-sales-management-api to 1.0.6

- env/requirements.yaml
chore: Promote foxtel-platform-general-authentication-service to version 1.0.1
> chore: foxtel-platform-general-authentication-service to 1.0.1

- env/requirements.yaml
chore: Promote foxtel-platform-general-payment-management-api to version 1.0.7
> chore: foxtel-platform-general-payment-management-api to 1.0.7

- env/requirements.yaml
chore: Promote foxtel-platform-general-device-management-api to version 1.0.8
> chore: foxtel-platform-general-device-management-api to 1.0.8

- env/requirements.yaml
chore: Promote foxtel-platform-general-payment-management-api to version 1.0.8
> chore: foxtel-platform-general-payment-management-api to 1.0.8

- env/requirements.yaml
chore: Promote foxtel-platform-general-authentication-service to version 1.0.5
> chore: foxtel-platform-general-authentication-service to 1.0.5

- env/requirements.yaml
chore: Promote foxtel-platform-general-device-management-api to version 1.0.12
> chore: foxtel-platform-general-device-management-api to 1.0.12

- env/requirements.yaml
chore: Promote foxtel-platform-general-device-management-api to version 1.0.13
> chore: foxtel-platform-general-device-management-api to 1.0.13

- env/foxtel-platform-general-fieldservice-api-values.yaml
- env/requirements.yaml
chore: Promote foxtel-platform-general-fieldservice-api to version 1.0.2
> chore: foxtel-platform-general-fieldservice-api to 1.0.2

- env/requirements.yaml
chore: Promote foxtel-platform-general-sales-management-api to version 1.0.10
> chore: foxtel-platform-general-sales-management-api to 1.0.10

- env/requirements.yaml
chore: Promote foxtel-platform-general-sales-management-api to version 1.0.11
> chore: foxtel-platform-general-sales-management-api to 1.0.11

- env/requirements.yaml
chore: Promote foxtel-platform-general-account-management-api to version 1.0.25
> chore: foxtel-platform-general-account-management-api to 1.0.25

- env/requirements.yaml
chore: Promote foxtel-platform-general-communication-api to version 1.0.5
> chore: foxtel-platform-general-communication-api to 1.0.5

- env/requirements.yaml
chore: Promote foxtel-platform-general-payment-management-api to version 1.0.11
> chore: foxtel-platform-general-payment-management-api to 1.0.11
